version: "3.7"

services:
  fastapi:
    image: fastapi
    command: sh -c "alembic upgrade head&&uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app

volumes:
  postgres-data:
    driver: local